const Types = {
    LOAD_PRODUCTS : 'LOAD_PRODUCTS',
    SET_SHOP : 'SET_SHOP',
    SET_USER : 'SET_USER',
    SET_SESSION: 'SET_SESSION',
    SET_COLLECTION: 'SET_COLLECTION',
    GET_PRODUCT: 'GET_PRODUCT',
    GET_PROFILE: 'GET_PROFILE',
    CREATE_CHECKOUT: 'CREATE_CHECKOUT',
    ADD_CHECKOUT: 'ADD_CHECKOUT',
    GET_CHECKOUT: 'GET_CHECKOUT',
    REMOVE_CHECKOUT: 'REMOVE_CHECKOUT',
    REPLACE_ITEM: 'REPLACE_ITEM',
    CREATE_ADDRESS: 'CREATE_ADDRESS',
    GET_ORDERS: 'GET_ORDERS',
}

export default Types;