// Generated by https://quicktype.io

export interface Data {
    data: DataClass;
}

export interface DataClass {
    products: Products;
}

export interface Products {
    edges: Edge[];
}

export interface Edge {
    node: Node;
}

export interface Node {
    id:              string;
    createdAt:       string;
    description:     string;
    descriptionHtml: string;
    productType:     string;
    publishedAt:     string;
    title:           string;
    updatedAt:       string;
    totalInventory:  number;
}
