// Generated by https://quicktype.io
export interface Data {
    shop: Shop;
}

export interface Shop {
    name:        string;
    description: null;
    products:    Products;
}

export interface Products {
    pageInfo: PageInfo;
    edges:    ProductsEdge[];
}

export interface ProductsEdge {
    cursor: string;
    node:   PurpleNode;
}

export interface PurpleNode {
    id:               string;
    title:            string;
    description:      string;
    availableForSale: boolean;
    productType:      string;
    onlineStoreUrl:   null;
    options:          Option[];
    variants:         Variants;
    images:           Images;
}

export interface Images {
    pageInfo: PageInfo;
    edges:    ImagesEdge[];
}

export interface ImagesEdge {
    node: ImageClass;
}

export interface ImageClass {
    src: string;
}

export interface PageInfo {
    hasNextPage:     boolean;
    hasPreviousPage: boolean;
}

export interface Option {
    id:     string;
    name:   Name;
    values: string[];
}

export enum Name {
    Meal = "Meal",
    Title = "Title",
}

export interface Variants {
    pageInfo: PageInfo;
    edges:    VariantsEdge[];
}

export interface VariantsEdge {
    node: FluffyNode;
}

export interface FluffyNode {
    id:              string;
    title:           string;
    selectedOptions: SelectedOption[];
    image:           ImageClass | null;
    price:           string;
    compareAtPrice:  null | string;
}

export interface SelectedOption {
    name:  Name;
    value: string;
}
